import express from "express";
import { Op } from "sequelize";
import auth from "../middlewares/auth.js";
import TransportSettings from "../models/TransportSettings.js";
import LogisticsRegion from "../models/LogisticsRegion.js";
import TransportVehicle from "../models/TransportVehicle.js";
import TransportJob from "../models/TransportJob.js";
import TransportEvent from "../models/TransportEvent.js";
import TransportMessageLog from "../models/TransportMessageLog.js";
import Appointment from "../models/Appointment.js";
import Custumers from "../models/Custumers.js";
import { distanceKm, geocodeAddress, nearestRegion, optimizeNearestNeighbor, summarizeRoute } from "../service/transportGeo.js";
import { sendTransportCustomerMessage } from "../service/transportWhatsapp.js";

const router = express.Router();
const tenant = (req) => req.user.establishment;
const defaults = { enabled: false, optimizationLevel: "basic", maxRegionDistanceKm: 2, whatsappEnabled: false, whatsappEvents: { pickup_started: true, delivery_started: true }, messageTemplates: {}, provider: "openstreetmap" };
const numberOrNull = (value) => value === "" || value == null || !Number.isFinite(Number(value)) ? null : Number(value);
const validCoordinate = (lat, lng) => lat != null && lng != null && Number(lat) >= -90 && Number(lat) <= 90 && Number(lng) >= -180 && Number(lng) <= 180;
const dateWindow = (date) => ({ [Op.between]: [new Date(`${date}T00:00:00`), new Date(`${date}T23:59:59.999`)] });
const regionPayload = (body = {}) => ({ code: String(body.code || "").trim().toUpperCase().slice(0, 16), name: String(body.name || "").trim().slice(0, 100), color: /^#[0-9a-f]{6}$/i.test(String(body.color || "")) ? body.color : "#f59e0b", centerLat: numberOrNull(body.centerLat), centerLng: numberOrNull(body.centerLng), radiusKm: Math.max(.1, Math.min(100, Number(body.radiusKm) || 2)), active: body.active !== false });
const activeRegions = (usersId) => LogisticsRegion.findAll({ where: { usersId, active: true } });
async function resolveRegion(usersId, point, maxKm) { return point ? nearestRegion(point, await activeRegions(usersId), maxKm) : null; }

router.get("/transport/settings", auth, async (req, res) => { const row = await TransportSettings.findOne({ where: { usersId: tenant(req) } }); res.json({ data: { ...defaults, ...(row?.toJSON?.() || {}) } }); });
router.put("/transport/settings", auth, async (req, res) => { const allowed = ["enabled", "optimizationLevel", "maxRegionDistanceKm", "whatsappEnabled", "whatsappEvents", "messageTemplates", "fuelPrice", "provider"], payload = { usersId: tenant(req) }; for (const key of allowed) if (req.body?.[key] !== undefined) payload[key] = req.body[key]; if (payload.optimizationLevel && !["basic", "smart", "complete"].includes(payload.optimizationLevel)) payload.optimizationLevel = "basic"; const [row] = await TransportSettings.upsert(payload, { returning: true }); res.json({ data: row }); });

router.post("/transport/geocode", auth, async (req, res) => { const address = String(req.body?.address || "").trim(); if (address.length < 5) return res.status(400).json({ message: "Informe um endereço completo para localizar." }); const point = await geocodeAddress(address); if (!point) return res.status(422).json({ message: "Não encontramos esse endereço no mapa." }); res.json({ data: point }); });

router.get("/transport/regions", auth, async (req, res) => res.json({ data: await LogisticsRegion.findAll({ where: { usersId: tenant(req) }, order: [["active", "DESC"], ["code", "ASC"]] }) }));
router.post("/transport/regions", auth, async (req, res) => { const payload = regionPayload(req.body); if (!payload.code || !payload.name) return res.status(400).json({ message: "Código e nome da região são obrigatórios." }); if (!validCoordinate(payload.centerLat, payload.centerLng)) return res.status(400).json({ message: "Localize o centro da região no mapa antes de salvar." }); const row = await LogisticsRegion.create({ ...payload, usersId: tenant(req) }); res.status(201).json({ data: row }); });
router.put("/transport/regions/:id", auth, async (req, res) => { const row = await LogisticsRegion.findOne({ where: { id: req.params.id, usersId: tenant(req) } }); if (!row) return res.status(404).json({ message: "Região não encontrada." }); const payload = regionPayload({ ...row.toJSON(), ...req.body }); if (!payload.code || !payload.name || !validCoordinate(payload.centerLat, payload.centerLng)) return res.status(400).json({ message: "Preencha nome, código e localização válida." }); await row.update(payload); res.json({ data: row }); });
router.delete("/transport/regions/:id", auth, async (req, res) => { const usersId = tenant(req), id = req.params.id; await Promise.all([Custumers.update({ logisticsRegionId: null }, { where: { usersId, logisticsRegionId: id } }), TransportJob.update({ regionId: null }, { where: { usersId, regionId: id } })]); await LogisticsRegion.destroy({ where: { id, usersId } }); res.status(204).end(); });

router.get("/transport/vehicles", auth, async (req, res) => res.json({ data: await TransportVehicle.findAll({ where: { usersId: tenant(req) }, order: [["active", "DESC"], ["name", "ASC"]] }) }));
router.post("/transport/vehicles", auth, async (req, res) => res.status(201).json({ data: await TransportVehicle.create({ ...req.body, usersId: tenant(req) }) }));
router.put("/transport/vehicles/:id", auth, async (req, res) => { const row = await TransportVehicle.findOne({ where: { id: req.params.id, usersId: tenant(req) } }); if (!row) return res.status(404).json({ message: "Veículo não encontrado." }); await row.update(req.body); res.json({ data: row }); });

router.post("/transport/customers/:id/geocode", auth, async (req, res) => { const usersId = tenant(req), customer = await Custumers.findOne({ where: { id: req.params.id, usersId } }); if (!customer) return res.status(404).json({ message: "Cliente não encontrado." }); const address = [customer.address, customer.bairro, customer.city, customer.state, "Brasil"].filter(Boolean).join(", "); const point = await geocodeAddress(address); if (!point) { await customer.update({ geocodeStatus: "failed" }); return res.status(422).json({ message: "Não conseguimos identificar este endereço no mapa." }); } const settings = await TransportSettings.findOne({ where: { usersId } }), match = await resolveRegion(usersId, point, settings?.maxRegionDistanceKm || 2); await customer.update({ latitude: point.lat, longitude: point.lng, geocodedAt: new Date(), geocodeStatus: "located", logisticsRegionId: match?.region?.id || null }); res.json({ data: { ...point, region: match?.region || null } }); });
router.post("/transport/customers/geocode-pending", auth, async (req, res) => { const usersId = tenant(req), limit = Math.min(50, Math.max(1, Number(req.body?.limit) || 20)), customers = await Custumers.findAll({ where: { usersId, [Op.or]: [{ geocodeStatus: { [Op.ne]: "located" } }, { geocodeStatus: null }] }, limit, order: [["updatedAt", "DESC"]] }); const settings = await TransportSettings.findOne({ where: { usersId } }); let located = 0, failed = 0; for (const customer of customers) { const address = [customer.address, customer.bairro, customer.city, customer.state, "Brasil"].filter(Boolean).join(", "); try { const point = await geocodeAddress(address); if (!point) throw new Error("not-found"); const match = await resolveRegion(usersId, point, settings?.maxRegionDistanceKm || 2); await customer.update({ latitude: point.lat, longitude: point.lng, geocodedAt: new Date(), geocodeStatus: "located", logisticsRegionId: match?.region?.id || null }); located += 1; } catch { await customer.update({ geocodeStatus: "failed" }); failed += 1; } } res.json({ data: { processed: customers.length, located, failed } }); });
router.put("/transport/customers/:id/preferences", auth, async (req, res) => { const customer = await Custumers.findOne({ where: { id: req.params.id, usersId: tenant(req) } }); if (!customer) return res.status(404).json({ message: "Cliente não encontrado." }); await customer.update({ taxiDogNotifications: req.body?.taxiDogNotifications || {}, logisticsRegionId: req.body?.logisticsRegionId ?? customer.logisticsRegionId }); res.json({ data: customer }); });

router.get("/transport/suggestions", auth, async (req, res) => { const usersId = tenant(req), customer = await Custumers.findOne({ where: { id: req.query.customerId, usersId } }); if (!customer) return res.status(404).json({ message: "Cliente não encontrado." }); let region = customer.logisticsRegionId ? await LogisticsRegion.findOne({ where: { id: customer.logisticsRegionId, usersId } }) : null; if (!region && customer.latitude != null && customer.longitude != null) { const settings = await TransportSettings.findOne({ where: { usersId } }), match = await resolveRegion(usersId, { lat: Number(customer.latitude), lng: Number(customer.longitude) }, settings?.maxRegionDistanceKm || 2); region = match?.region || null; if (region) await customer.update({ logisticsRegionId: region.id }); } const date = String(req.query.date || "").slice(0, 10), appointments = await Appointment.findAll({ attributes: ["id", "time"], where: { usersId, date: dateWindow(date) } }), timeById = new Map(appointments.map((item) => [String(item.id), String(item.time || "").slice(0, 5)])), jobs = region ? await TransportJob.findAll({ where: { usersId, regionId: region.id, appointmentId: { [Op.in]: [...timeById.keys()] } } }) : [], times = [...new Set(jobs.map((job) => job.pickupTime?.slice?.(0, 5) || timeById.get(String(job.appointmentId))).filter(Boolean))].sort(); res.json({ data: { region, nearbyCount: jobs.length, recommendedTimes: times.slice(0, 4), message: region && jobs.length ? `Já existem ${jobs.length} transporte(s) da região ${region.code} nesta data.` : region ? `Cliente da região ${region.code}. Ainda não há rota agrupada nesta data.` : "Localização ou região pendente." } }); });

router.get("/transport/jobs", auth, async (req, res) => { const usersId = tenant(req), date = String(req.query.date || "").slice(0, 10), appointments = await Appointment.findAll({ attributes: ["id"], where: { usersId, ...(date ? { date: dateWindow(date) } : {}) } }), ids = appointments.map((item) => item.id), jobs = ids.length ? await TransportJob.findAll({ where: { usersId, appointmentId: { [Op.in]: ids } }, order: [["routeSequence", "ASC"], ["pickupTime", "ASC"]] }) : [], regionIds = [...new Set(jobs.map((item) => item.regionId).filter(Boolean))], vehicleIds = [...new Set(jobs.map((item) => item.vehicleId).filter(Boolean))], [regions, vehicles] = await Promise.all([regionIds.length ? LogisticsRegion.findAll({ where: { id: { [Op.in]: regionIds }, usersId } }) : [], vehicleIds.length ? TransportVehicle.findAll({ where: { id: { [Op.in]: vehicleIds }, usersId } }) : []]), byRegion = new Map(regions.map((item) => [String(item.id), item.toJSON()])), byVehicle = new Map(vehicles.map((item) => [String(item.id), item.toJSON()])); res.json({ data: jobs.map((item) => ({ ...item.toJSON(), region: byRegion.get(String(item.regionId)) || null, vehicle: byVehicle.get(String(item.vehicleId)) || null })) }); });
router.get("/transport/jobs/appointment/:appointmentId", auth, async (req, res) => res.json({ data: await TransportJob.findOne({ where: { appointmentId: req.params.appointmentId, usersId: tenant(req) } }) }));
router.put("/transport/jobs/:id", auth, async (req, res) => { const row = await TransportJob.findOne({ where: { id: req.params.id, usersId: tenant(req) } }); if (!row) return res.status(404).json({ message: "Transporte não encontrado." }); const allowed = ["driverId", "driverName", "vehicleId", "pickupTime", "deliveryTime", "regionId", "notes"], payload = {}; for (const key of allowed) if (req.body?.[key] !== undefined) payload[key] = req.body[key] || null; await row.update(payload); res.json({ data: row }); });
router.post("/transport/jobs", auth, async (req, res) => { const usersId = tenant(req), appointment = await Appointment.findOne({ where: { id: req.body.appointmentId, usersId } }); if (!appointment) return res.status(404).json({ message: "Agendamento não encontrado." }); const payload = { ...req.body, usersId }; if (!validCoordinate(payload.latitude, payload.longitude) && String(payload.pickupAddress || payload.deliveryAddress || "").trim()) { try { const point = await geocodeAddress(payload.pickupAddress || payload.deliveryAddress), settings = await TransportSettings.findOne({ where: { usersId } }), match = await resolveRegion(usersId, point, settings?.maxRegionDistanceKm || 2); if (point) Object.assign(payload, { latitude: point.lat, longitude: point.lng, geocodeStatus: "located", regionId: match?.region?.id || null }); else payload.geocodeStatus = "failed"; } catch { payload.geocodeStatus = "pending"; } } const [job] = await TransportJob.upsert(payload, { returning: true }); res.json({ data: job }); });
router.delete("/transport/jobs/appointment/:appointmentId", auth, async (req, res) => { await TransportJob.destroy({ where: { appointmentId: req.params.appointmentId, usersId: tenant(req) } }); res.status(204).end(); });
router.get("/transport/jobs/:id/history", auth, async (req, res) => res.json({ data: await TransportEvent.findAll({ where: { transportJobId: req.params.id, usersId: tenant(req) }, order: [["createdAt", "ASC"]] }) }));
router.post("/transport/jobs/:id/status", auth, async (req, res) => { const usersId = tenant(req), job = await TransportJob.findOne({ where: { id: req.params.id, usersId } }); if (!job) return res.status(404).json({ message: "Transporte não encontrado." }); const next = String(req.body.status || ""), previous = job.status, eventType = String(req.body.eventType || next), key = `${job.id}:${eventType}:${new Date().toISOString().slice(0, 10)}`; await job.update({ status: next, driverId: req.body.driverId || job.driverId }); await TransportEvent.create({ usersId, transportJobId: job.id, appointmentId: job.appointmentId, eventType, previousStatus: previous, newStatus: next, actorId: req.user.id, actorName: "Equipe", metadata: { sendWhatsapp: Boolean(req.body.sendWhatsapp) } }); let whatsapp = { status: "not_requested" }; if (req.body.sendWhatsapp) { const existing = await TransportMessageLog.findOne({ where: { idempotencyKey: key, usersId } }); if (existing?.status === "sent") whatsapp = { status: existing.status, duplicatePrevented: true }; else { const log = existing || await TransportMessageLog.create({ usersId, transportJobId: job.id, eventType, idempotencyKey: key, status: "pending" }); try { const sent = await sendTransportCustomerMessage({ appointmentId: job.appointmentId, eventType }); await log.update({ status: sent.status, message: sent.message || null, recipient: sent.recipient || null, sentAt: sent.status === "sent" ? new Date() : null, error: null }); whatsapp = sent; } catch (error) { await log.update({ status: "failed", error: error.message }); whatsapp = { status: "failed", retryable: true }; } } } res.json({ data: job, whatsapp }); });

router.post("/transport/optimize", auth, async (req, res) => { const usersId = tenant(req), settings = await TransportSettings.findOne({ where: { usersId } }), level = settings?.optimizationLevel || "basic", jobs = await TransportJob.findAll({ where: { usersId, id: { [Op.in]: req.body.jobIds || [] } } }); let start = req.body.start && validCoordinate(req.body.start.lat, req.body.start.lng) ? { lat: Number(req.body.start.lat), lng: Number(req.body.start.lng) } : null; if (!start && req.body.startAddress) start = await geocodeAddress(req.body.startAddress); const located = jobs.filter((item) => validCoordinate(item.latitude, item.longitude)).map((item) => ({ ...item.toJSON(), lat: Number(item.latitude), lng: Number(item.longitude) })), pending = jobs.filter((item) => !validCoordinate(item.latitude, item.longitude)).map((item) => ({ ...item.toJSON(), distanceFromPreviousKm: 0 })); let ordered; if (level === "basic") ordered = [...located].sort((a, b) => String(a.regionId || "zzz").localeCompare(String(b.regionId || "zzz")) || String(a.pickupTime || a.deliveryTime || "").localeCompare(String(b.pickupTime || b.deliveryTime || ""))); else if (level === "smart") { const groups = new Map(); for (const item of located) { const key = String(item.regionId || "sem-regiao"); if (!groups.has(key)) groups.set(key, []); groups.get(key).push(item); } ordered = [...groups.values()].flatMap((group) => optimizeNearestNeighbor(group, start)); } else ordered = optimizeNearestNeighbor(located, start); ordered = [...ordered, ...pending]; if (level === "basic") ordered = ordered.map((item, index) => ({ ...item, distanceFromPreviousKm: index ? Number(distanceKm(ordered[index - 1], item)?.toFixed(2) || 0) : start ? Number(distanceKm(start, item)?.toFixed(2) || 0) : 0 })); const summary = summarizeRoute(ordered); let elapsed = 0; await Promise.all(ordered.map((item, index) => { elapsed += index ? Math.round((Number(item.distanceFromPreviousKm || 0) / 28) * 60) + 5 : 0; item.etaMinutes = elapsed; item.routeSequence = index + 1; return TransportJob.update({ routeSequence: index + 1, etaMinutes: elapsed }, { where: { id: item.id, usersId } }); })); res.json({ data: ordered, summary: { ...summary, located: located.length, pending: pending.length, level } }); });

export default router;
